[package]
name = "serial2"
version = "0.1.0"
edition = "2021"

[target.'cfg(unix)'.dependencies]
libc = "0.2.97"

[target.'cfg(windows)'.dependencies]
winapi = { version = "0.3.9", features = ["commapi", "std", "winbase"] }
